---
title: Piecewise function to down-sample mutations in PCAWG spectra
author: Wu, Yang
date: "`r Sys.Date()`"
GitHub: WuyangFF95
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    latex_engine: xelatex
---

# 0. Load prerequisites

```{r, echo = FALSE}
require(ggplot2)
```

# 1. Definition of a piecewise function.

This function aims to lower the mutation counts in some hyper-mutated mutational spectra (e.g. spectra with Pol-Epsilon activity or UV exposure). On the other hand, it keeps the mutational spectra with normal or low mutation counts as they are.

```{r}
source("down_sample.R")
print(down_sample_func) # Print the source code
```


# 2. Plotting the function

```{r}
x_vec <- seq(0, 1e+06, 1000)
y_df <- data.frame()
thres_vals <- c(1000, 5000, 10000)
for (thres_val in thres_vals) {
  y_df <- rbind(
    y_df,
    data.frame(
      thres = thres_val,
      x = x_vec,
      y = sapply(x_vec, down_sample_func, thres = thres_val)))
}

ggObj <- 
  ggplot2::ggplot(y_df, xlab = "Mutations",
                  ylab = "Transformed mutations") +
  geom_point(mapping = aes(x = x, y = y, color = as.factor(thres))) +
  guides(color = guide_legend(title = "Threshold"))
ggObj
```


# 3. Print version

```{r}
version
```